### ISSUE TITLE
S2E cannot be compiled successfully

### ISSUE THREAD

**Issue by m4p1e** [secure-php/sia#1]
The Makefile and multiple necessary files are missing in the S2E source folder.

**Comment by peng-hui** [comment]
I will take a look in the coming weeks (it may be earlier than that). The tool generally needs to build s2e with our modification and then start a new s2e project. Since s2e is a large project with several dependencies hosted in its s2e's github, the current symphp repository wanted to have all code downloaded readily.

**Comment by peng-hui** [comment]
I updated the code to fix this issue. I reorganized the code structure like s2e. I ported my changes from older s2e to the last and pushed my changes as a separate commit. I was able to build the modified s2e within a docker container running ubuntu 22.04.

**Comment by m4p1e** [comment]
Many thanks for the prompt reply. I have another question: Does the repo include complete the modification of php-src and s2e ?
